
name: "Hello Action"
description: "Prints a hello message"

inputs:
  environment:
    description: "Name of the environment"
    required: true

runs:
  using: "composite"
  steps:
    - name: ACR Import
      uses: ./.github/actions/deployment_promotion/acr_import
      with:
        environment: ${{ inputs.environment }}

    - name: Deployment
      uses: ./.github/actions/deployment_promotion/deployment
      with:
        environment: ${{ inputs.environment }}

    - name: Check Deployment
      uses: ./.github/actions/deployment_promotion/check_deployment
      with:
        environment: ${{ inputs.environment }}

    - name: Clean Cache
      uses: ./.github/actions/deployment_promotion/clean_cache
      with:
        environment: ${{ inputs.environment }}